### ISSUE TITLE
[Q] Frontend for docs

### ISSUE THREAD

**Issue by rakesh4real** [koaning/human-learn#28]
Hi, Just a silly question, may I know what tool and **theme/template** are you using for docs? Looks like you are using Jekyll can I replicate it by simply forking the repo and running something like `jekyll serve`

**Comment by rakesh4real** [comment]
Never mind, got it! Material fro MkDocs

**Comment by koaning** [comment]
You might appreciate this tutorial. It's a different project but it shows how I set up the docs https://calmcode.io/docs/introduction.html
