### ISSUE TITLE
Bokeh Port Error

### ISSUE THREAD

**Issue by koaning** [koaning/human-learn#37]
Sometimes I hit this error:

```
ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'http://localhost:8889';                       use --allow-websocket-origin=localhost:8889 or set BOKEH_ALLOW_WS_ORIGIN=localhost:8889 to permit this; currently we allow origins {'localhost:8888'}
WARNING:tornado.access:403 GET /ws (::1) 1.65ms
```

Would be nice to get an automated fix for this.

**Comment by koaning** [comment]
This is [related](https://github.com/bokeh/bokeh/issues/8096#issuecomment-406815954) to something
bokeh cannot do without explicit permission from jupyter. It can't be fixed by this library but I added something to the FAQ to explain.

**Comment by nthomsencph** [comment]
Hi, 
Spent quite some time on this issue. Couldn't get around displaying the charts in in VSC notebooks as per #https://github.com/koaning/human-learn/issues/67 
Exporting the variable in `~/.bashrc` didn't work either for me for some reason.
When encountering this issue, I solved it by explicitly setting

`import os
os.environ["BOKEH_ALLOW_WS_ORIGIN"] = "localhost:8889"`

And then running 
`charts = InteractiveCharts(df.loc[lambda d: d['label'] == ''], labels = ['group'])
charts.add_chart(x = "dim1", y = "dim2")` 
normally, as Vincent does in [PyData Riyadh](https://www.youtube.com/watch?v=nCA8P9OEcQc)

Hope this helps

**Comment by koaning** [comment]
@nthomsencph feel free to make a PR :) !
