### ISSUE TITLE
Running into a traceback error when importing the interactive charts module 

### ISSUE THREAD

**Issue by aishnaga** [koaning/human-learn#40]
I am trying to run the interactive classifier notebook downloaded from the link at the bottom of this page - https://koaning.github.io/human-learn/guide/drawing-classifier/drawing.html.

This is being run on a Windows x86-64 laptop, with the latest minconda3, python3.8 and jupyter-lab. I run into a traceback error on cell 3 
`from hulearn.experimental.interactive import InteractiveCharts, InteractiveChart 
`

```
ImportError                               Traceback (most recent call last)
<ipython-input-3-9933ce75800d> in <module>()
----> 1 from hulearn.experimental.interactive import InteractiveCharts, InteractiveChart

ImportError: cannot import name 'InteractiveChart' from 'hulearn.experimental.interactive' (C:\<mypath>\miniconda3\envs\myenv\lib\site-packages\hulearn\experimental\interactive.py)
```

Not able to figure out what's up; issue reproduces on a unix environment (on Mac) as well.

**Comment by koaning** [comment]
Note to self; I should add unit tests on those notebooks. 

Working on it here; https://github.com/koaning/human-learn/pull/41

**Comment by koaning** [comment]
The bug was in the notebook but it should be fixed now. 

I've got a nice little setup that tests the notebooks. I'll need to see if I can do something similar to the actual docs/guides themselves.

**Comment by koaning** [comment]
Another part of the issue here is that I remained `InteractiveChart` to `SingleInteractiveChart`. It's meant to be an internal chart.

**Comment by koaning** [comment]
Yeah testing the docs themselves is tricky. The tools are really specific to jupyter and may crash if we use a tool like [exdown](https://github.com/nschloe/exdown) to automatically fetch/run the code from the command line. 

I'll consider the issue fixed, but @aishnaga feel free to reopen if you think there's still an issue.
