### ISSUE TITLE
Adding a tooltip would help make decision on where to draw the line when no labels are available

### ISSUE THREAD

**Issue by nbeuchat** [koaning/human-learn#47]
Hey there! Human learn has been super helpful so far. One thing I am a bit missing is the ability to see some of the underlying data about each data point. It would be very helpful to have a tooltip and having the option to pick a list of columns from the data frame to see in the tooltip. 

Right now, I am using Plotly separately to do that which allows me to more easily explore clusters. Then I try to find this cluster and draw on it. 

![Screenshot 2021-01-14 19:22:32](https://user-images.githubusercontent.com/8236283/104632580-32adbb00-569e-11eb-982c-07726bc45862.png)

What do you think?
Cheers,
Nicolas

**Comment by nbeuchat** [comment]
Looks like Bokeh has this option: https://github.com/bokeh/bokeh/blob/43ff5af6f666cbf4d1ed1c26c7a128e9b10cd86c/examples/app/movies/main.py#L54

Maybe one simple option would be to allow passing down kwargs to bokeh `figure` method?

**Comment by phurwicz** [comment]
I'm happy to delete my comment if it cuts the discussion away.. but perhaps this can help?

 [`hover`](https://github.com/phurwicz/hover) does almost exactly what you are looking for (identifying clusters with tooltips, especially without existing labels), except that instead of making a model like in `hulearn` you just apply a label of your choice.

**Comment by nbeuchat** [comment]
@phurwicz Thank you very much for the link to `hover`, I didn't know this tool. It looks like a really good interface for bulk adding labels. I'll give it a shot now!

I still think having the tooltip in `hulearn` would be great so as to avoid having to add an extra step if it is not necessary.

**Comment by phurwicz** [comment]
> @phurwicz Thank you very much for the link to `hover`, I didn't know this tool. It looks like a really good interface for bulk adding labels. I'll give it a shot now!
> 
> I still think having the tooltip in `hulearn` would be great so as to avoid having to add an extra step if it is not necessary.

Agreed! Showing custom tooltips can be tricky but is definitely worth it.

Here's an [my implementation](https://github.com/phurwicz/hover/blob/main/hover/core/explorer/local_config.py) if it helps bringing tooltips to `hulearn`.

**Comment by koaning** [comment]
For some reason GitHub wasn't notifying me of these messages. I only just now realized this conversation was happening. Am working on a PR right now https://github.com/koaning/human-learn/pull/55/files though to get this feature in.

**Comment by nbeuchat** [comment]
No worries at all! It's awesome that someone took the time to open a PR for it, looking forward to trying it once/if it's merged!

**Comment by koaning** [comment]
Closing due to radio silence.
