### ISSUE TITLE
Adding common accessor for changing Chart Title, Legend Names, x label, y label etc

### ISSUE THREAD

**Issue by tvash** [koaning/human-learn#49]
Currently, the library does not support adding custom title rather the x and y labels passed to the Interactive chart becomes the title 

`self.plot = figure(width=width, height=height, title=f"{x} vs. {y}")`

as shown above we can add common accessors to deal with this?

**Comment by koaning** [comment]
Since the charts are meant to be temporary tools to draw shapes for the classifier it didn't occur to me that folks would want to change the title. Could you explain the use-case a bit more?

**Comment by koaning** [comment]
Closing due to radio silence.
