### ISSUE TITLE
RuleBasedClassifier

### ISSUE THREAD

**Issue by koaning** [koaning/human-learn#5]
We want to have classifiers that contain simple if statements as logic which could potentially be exported as SQL.

**Comment by jgendrinal** [comment]
Does this mean that the if statements will be translated into a list of `where` clauses?

**Comment by koaning** [comment]
I'd imagine they get translate to `CASE WHEN` but the implementation will probably not involve translating python `if` statments. Rather we'll probably build a UI that makes it easy to construct and we'll serialize is via something json. 

This has not been designed yet in any detail yet, but I imagine this is the way forward for this feature.
