### ISSUE TITLE
AttributeError: module 'tornado.ioloop' has no attribute '_Selectable'

### ISSUE THREAD

**Issue by 123nishant** [koaning/human-learn#59]
Hi Vincent, 

I was particularly impressed by how we could classify the data by just drawing.
Kudos to you. 

However, I have been trying to implement the same in a different dataset but it's repeatedly throwing the below error . 

I am also linking my notebook just in case : 
https://www.kaggle.com/nishantrock/notebook8935105440

Do suggest why this error is happening. I've tried it multiple times but it throws the same error. 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-78-c3c8a95370ef> in <module>
----> 1 clf.add_chart(x = 'Health Indicator', y = 'Reco_Policy_Premium')

/opt/conda/lib/python3.7/site-packages/hulearn/experimental/interactive.py in add_chart(self, x, y, size, alpha, width, height, legend)
     97         )
     98         self.charts.append(chart)
---> 99         chart.show()
    100 
    101     def data(self):

/opt/conda/lib/python3.7/site-packages/hulearn/experimental/interactive.py in show(self)
    199 
    200     def show(self):
--> 201         show(self.app)
    202 
    203     def _replace_xy(self, data):

/opt/conda/lib/python3.7/site-packages/bokeh/io/showing.py in show(obj, browser, new, notebook_handle, notebook_url, **kw)
    135     # in Tornado) just in order to show a non-server object
    136     if is_application or callable(obj):
--> 137         return run_notebook_hook(state.notebook_type, 'app', obj, state, notebook_url, **kw)
    138 
    139     return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)

/opt/conda/lib/python3.7/site-packages/bokeh/io/notebook.py in run_notebook_hook(notebook_type, action, *args, **kw)
    296     if _HOOKS[notebook_type][action] is None:
    297         raise RuntimeError("notebook hook for %r did not install %r action" % notebook_type, action)
--> 298     return _HOOKS[notebook_type][action](*args, **kw)
    299 
    300 #-----------------------------------------------------------------------------

/opt/conda/lib/python3.7/site-packages/bokeh/io/notebook.py in show_app(app, state, notebook_url, port, **kw)
    463 
    464     from tornado.ioloop import IOLoop
--> 465     from ..server.server import Server
    466 
    467     loop = IOLoop.current()

/opt/conda/lib/python3.7/site-packages/bokeh/server/server.py in <module>
     39 # External imports
     40 from tornado import version as tornado_version
---> 41 from tornado.httpserver import HTTPServer
     42 from tornado.ioloop import IOLoop
     43 

/opt/conda/lib/python3.7/site-packages/tornado/httpserver.py in <module>
     30 
     31 from tornado.escape import native_str
---> 32 from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
     33 from tornado import httputil
     34 from tornado import iostream

/opt/conda/lib/python3.7/site-packages/tornado/http1connection.py in <module>
     32 from tornado import gen
     33 from tornado import httputil
---> 34 from tornado import iostream
     35 from tornado.log import gen_log, app_log
     36 from tornado.util import GzipDecompressor

/opt/conda/lib/python3.7/site-packages/tornado/iostream.py in <module>
    208 
    209 
--> 210 class BaseIOStream(object):
    211     """A utility class to write to and read from a non-blocking file or socket.
    212 

/opt/conda/lib/python3.7/site-packages/tornado/iostream.py in BaseIOStream()
    284         self._closed = False
    285 
--> 286     def fileno(self) -> Union[int, ioloop._Selectable]:
    287         """Returns the file descriptor for this stream."""
    288         raise NotImplementedError()

AttributeError: module 'tornado.ioloop' has no attribute '_Selectable'

**Comment by koaning** [comment]
I think the reason is that you're using kaggle notebooks. I don't support colab/kaggle notebooks, only jupyter ones. The reason is that google has somewhat different standards which don't play nice with many open source tools in the jupyter ecosystem (like Bokeh and ipywidgets).

**Comment by 123nishant** [comment]
Thank you for the information Vincent . 

I'll be on a lookout for these kind of scenarios.
