### ISSUE TITLE
charts not showing up in Visual Studio Code notebook

### ISSUE THREAD

**Issue by mschmill** [koaning/human-learn#67]
I am trying basically to reproduce the PyData Berlin environment using human-learn with sentence embeddings and UMAP so that I can draw boundaries, explore, and quickly label text data.

The problem I am having is that the human-learn charts are not rendering in the VSC notebook. VSC is using Jupyter for the notebook and I am on Windows. I can render Pyplot, Seaborn, even Bokeh into the notebooks but the human-learn charts do not display:

![image](https://user-images.githubusercontent.com/14186571/120686583-1fde2c00-c46f-11eb-8e24-708cae61f148.png)

Is anyone else having this issue? Is there some Jupyter extension I need or some Jupyter command I need to run?
Bokeh is 2.3.2, human-learn is 0.3.1

**Comment by koaning** [comment]
I think this is related to a bokeh issue. There's a similar problem on Google's colab environment. 

You can confirm that this issue doesn't occur on JupyterLab from the browser?

**Comment by koaning** [comment]
I'm curious if it's related to [this bokeh issue](https://github.com/koaning/human-learn/issues/37).

**Comment by koaning** [comment]
Closing due to radio silence.

**Comment by nthomsencph** [comment]
A hacky fix to get around this is to first provoke the error, then get the hash for your VSC session and finally set that as an environment variable. You get it from the value suggested from `BOKEH_ALLOW_WS_ORIGIN=<...>` as below.

```bash
ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'vscode-webview://013b0305-284d-4b85-a635-db4846bb34ba';                       use --allow-websocket-origin=013b0305-284d-4b85-a635-db4846bb34ca or set BOKEH_ALLOW_WS_ORIGIN=**013b0305-284d-4b85-a635-db4846bb34ca** to permit this; currently we allow origins {'localhost:8889'}
WARNING:tornado.access:403 GET /ws?id=013b0305-284d-4b85-a635-db4846bb34ba&swVersion=2&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (::1) 1.29ms
```

Then just import os and set the string as below. 

```python
import os
os["BOKEH_ALLOW_WS_ORIGIN"]="013b0305-284d-4b85-a635-db4846bb34ca"
```
