### ISSUE TITLE
Unable to draw in jupyter lab

### ISSUE THREAD

**Issue by zzzbobml** [koaning/human-learn#68]
When I click for drawing as per [this](https://koaning.github.io/human-learn/guide/drawing-classifier/drawing.html#from-jupyter) example, nothing happens. 
I've already enabled %matplotlib. Am I missing some other initialization?

**Comment by koaning** [comment]
I think you're trying to draw the interactive chart, which is based on bokeh, not matplotlib. 

Are you hsing jupyterlab or colab? Colab doesn't support bokeh unfortunately.

**Comment by koaning** [comment]
Could you share some code/screenshot/traceback that might help to explain what is going wrong?

**Comment by BSlience** [comment]
show nothing in jupyter lab
```
human-learn==0.3.1
jupyterlab==3.1.10
```
![image](https://user-images.githubusercontent.com/6592136/132617299-e559286a-7b1d-4297-8651-df5a401d7201.png)

**Comment by BSlience** [comment]
show nothing too
![image](https://user-images.githubusercontent.com/6592136/132633145-a0499415-76e4-4e50-83af-05142160f3d4.png)

**Comment by koaning** [comment]
Ah, you're tring to replicate the bulk-labelling demo. Technically, that's another repo. But let's see. 

Can you confirm that you're running everything on port 8888? Per [this issue](https://koaning.github.io/human-learn/examples/faq.html#im-getting-a-port-error).

**Comment by koaning** [comment]
In this case, could you also just try running human-learn without all the extra ipywidgets? That sure makes debugging a lot easier.

**Comment by koaning** [comment]
I can confirm something is up. It seems like bokeh and jupyter no longer play nice with each other.

**Comment by koaning** [comment]
OK. I just investigated and here's what I'm concluding. 

1. It *does* seem to work when I run it on my Linux machine. 
2. It *does not* seem to work when I run it on my Linux machine, but over SSH. It seems bokeh starts up a separate process and service that is handling all the rendering. Since my SSH port only opens up port 8888, it's blocking the ports from bokeh. 

Just to confirm, @BSlience does this maybe explain whats happening on your end?

**Comment by Borg93** [comment]
![image](https://user-images.githubusercontent.com/48671678/134000836-083212bd-cc6b-48b4-83d5-7c9d67297e07.png)
getting the same error that I'm not able to select anything..

**Comment by koaning** [comment]
Just to make sure, you're able to make shapes by double-clicking? Just want to exclude that it's a UI-thing.

**Comment by Borg93** [comment]
Damn, you're right. I just saw the instructions inside the source code! Works :)

**Comment by roddyfue** [comment]
> I was facing this same issue when running over ssh and was able to solve it by forwarding the appropriate port and modifying the  InteractiveCharts class to take the port as a parameter when calling show() on the bokeh chart
