### ISSUE TITLE
fixing error "AttributeError: 'FunctionClassifier' object has no attribute 'classes_'" when running calmcode.io titanic example for GridSearchCV

### ISSUE THREAD

**Issue by ebbestubbe** [koaning/human-learn#82]
When running the calmcode.io example https://calmcode.io/human-learn/classifier.html I get the following error when running the grid search:

> File "c:\repos\titanic\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 136, in __call__
>     score = scorer._score(
>   File "c:\repos\titanic\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 353, in _score
>     y_pred = method_caller(estimator, "predict", X)
>   File "c:\repos\titanic\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 86, in _cached_call
>     result, _ = _get_response_values(
>   File "c:\repos\titanic\venv\lib\site-packages\sklearn\utils\_response.py", line 182, in _get_response_values
>     classes = estimator.classes_
> AttributeError: 'FunctionClassifier' object has no attribute 'classes_'

I fixed it locally by following this stackoverflow post https://stackoverflow.com/questions/75658274/gridsearchcv-object-has-no-attribute-classes 
to sklearn docs https://scikit-learn.org/stable/developers/develop.html .
In the file hulearn/classification/functionclassifier.py I added the import `from sklearn.utils.multiclass import unique_labels` 
And to the FunctionClassifier.fit line I added `self.classes_ = unique_labels(y)`
This fixed the issue for me, and I get the plot as expected.
I haven't tested this for anything else than the functionclassifier for this example, and I have not tested this with the builds or tests for the project, and I havent made a PR yet.

**Comment by koaning** [comment]
It might be time to upgrade the lower dependency of sklearn and to run a full suite of unit tests on that. It's certianly possible that some things have changed. 

If you're up for it I'm all ears for a PR, otherwise I'll just keep this issue open as a reminder and I'll try to get to it later. I have a child now, so I can't give an ETA.

**Comment by koaning** [comment]
I just published a release that should have this fix. Let me know if this issue persists.
